export const styles = {
  body: {
    fontFamily: '-apple-system, "Segoe UI", Arial, Helvetica, sans-serif',
    background: '#ffffff',
    color: '#393939',
    margin: 0,
    padding: '16px 18px 24px',
    fontSize: 14,
    lineHeight: 1.5
  },
  h1: {fontSize: 18, fontWeight: 500, margin: '0 0 4px', color: '#000'},
  h2: {fontSize: 14, fontWeight: 500, margin: '16px 0 6px', color: '#000'},
  sub: {fontSize: 12, color: '#777', margin: '0 0 16px'},
  kpiRef: {fontSize: 13, fontWeight: 500, color: '#777', letterSpacing: '0.02em'},
  layout: {display: 'grid', gridTemplateColumns: '280px minmax(0, 1fr)', gap: 16, alignItems: 'start'},
  sidebar: {position: 'sticky', top: 8, maxHeight: 'calc(100vh - 16px)', overflowY: 'auto'},
  main: {minWidth: 0, position: 'relative'},
  controls: {padding: 12, background: '#f8f6f1', borderRadius: 8, display: 'flex', flexDirection: 'column', gap: 9},
  panelTitle: {fontSize: 11, fontWeight: 500, color: '#777', textTransform: 'uppercase', letterSpacing: '0.06em', paddingBottom: 4, borderBottom: '0.5px solid #cfcdc6', marginBottom: 2},
  ctl: {display: 'flex', flexDirection: 'column', gap: 3, fontSize: 12},
  label: {color: '#555', fontWeight: 500, display: 'flex', justifyContent: 'space-between', alignItems: 'baseline', gap: 8, fontSize: 12},
  val: {color: '#ff4700', fontWeight: 500, fontSize: 13, whiteSpace: 'nowrap'},
  range: {width: '100%', accentColor: '#ff4700', height: 22, margin: 0},
  dateInput: {border: '0.5px solid #cfcdc6', borderRadius: 6, padding: '6px 8px', font: 'inherit', color: '#393939', background: '#fff', fontSize: 12},
  textInput: {border: '1px solid #cfcdc6', borderRadius: 4, padding: '3px 6px', font: 'inherit', color: '#393939', background: '#fff', fontSize: 11},
  btn: {background: '#fff', border: '0.5px solid #cfcdc6', borderRadius: 6, padding: '6px 10px', font: 'inherit', fontSize: 12, color: '#393939', cursor: 'pointer'},
  kpis: {display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: 12, margin: '0 0 18px'},
  kpi: {background: '#f8f6f1', borderRadius: 8, padding: '10px 12px'},
  kpiLbl: {fontSize: 11, color: '#777', textTransform: 'uppercase', letterSpacing: '0.04em'},
  kpiNum: {fontSize: 20, fontWeight: 500, color: '#000', marginTop: 2},
  kpiSub: {fontSize: 11, color: '#777', marginTop: 1},
  legend: {display: 'flex', gap: 14, fontSize: 11, color: '#555', margin: '0 0 4px', flexWrap: 'wrap'},
  swatch: {display: 'inline-block', width: 10, height: 10, borderRadius: 2, marginRight: 5, verticalAlign: 'middle'},
  table: {width: '100%', borderCollapse: 'collapse', fontSize: 12, marginTop: 6},
  th: {textAlign: 'left', padding: '5px 8px', borderBottom: '0.5px solid #e6e2db', background: '#f8f6f1', fontWeight: 500, color: '#555', fontSize: 11, textTransform: 'uppercase', letterSpacing: '0.03em'},
  td: {textAlign: 'left', padding: '5px 8px', borderBottom: '0.5px solid #e6e2db', fontVariantNumeric: 'tabular-nums'},
  actualBadge: {display: 'inline-block', background: '#e1f5ee', color: '#0f6e56', fontSize: 10, fontWeight: 500, padding: '1px 5px', borderRadius: 3, marginLeft: 4, letterSpacing: '0.02em'},
  deltaGreen: {display: 'inline-block', fontSize: 10, fontWeight: 500, padding: '1px 6px', borderRadius: 3, background: '#e1f5ee', color: '#0f6e56', marginLeft: 4},
  deltaAmber: {display: 'inline-block', fontSize: 10, fontWeight: 500, padding: '1px 6px', borderRadius: 3, background: '#faeeda', color: '#854f0b', marginLeft: 4},
  deltaRed: {display: 'inline-block', fontSize: 10, fontWeight: 500, padding: '1px 6px', borderRadius: 3, background: '#fcebeb', color: '#791f1f', marginLeft: 4},
  note: {fontSize: 11, color: '#888', marginTop: 6, lineHeight: 1.5}
};
